language: csharp
solution: TIK.sln
mono: none
dotnet: 2.0.0
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5


script:    # the following commands are just examples, use whatever your build process requires
  - dotnet restore ./TIK/TIK.sln
  - dotnet build ./TIK/TIK.sln -c Debug -f netcoreapp2.0