#docker-compose.override.yml (Extended config for DEVELOPMENT env.)
version: '2'

services:
# Simplified number of services here:
  tik.computation.akkaseed:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - TIK_AKKASEED_IP=0.0.0.0
    - TIK_AKKASEED_PORT=80
    - TIK_AKKASEED_HUCON=Hucon.txt
    - TIK_AKKASEED_ADDR=tik-akkaseed:5301
    - TIK_BATCH_URL=http://tik-batch
    - TIK_ACTORSYSTEM=OnlineSystem
    ports:
      - "5301:5301"
      - "5300:80"

  tik.processservice.online:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_ONLINE_IP=0.0.0.0
      - TIK_ONLINE_PORT=80
      - TIK_ONLINE_HUCON=Hucon.txt
      - TIK_AKKASEED_ADDR=tik-akkaseed:5301
      - TIK_BATCH_URL=http://tik-batch
      - TIK_ACTORSYSTEM=OnlineSystem
    ports:
      - "5101:80"

  tik.processservice.identity:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - TIK_IDENTITY_IP=0.0.0.0
    - TIK_IDENTITY_PORT=80
    ports:
      - "5100:80"

  tik.webportal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_WEBPORTAL_IP=0.0.0.0
      - TIK_WEBPORTAL_PORT=80
      - TIK_ONLINE_URL=http://tik-online
      - TIK_IDENTITY_URL=http://tik-identity
    ports:
      - "5000:80"
