#docker-compose.yml (Base)
version: '2'

services:
  tik.computation.akkaseed:
    image: tik.computation.akkaseed
    container-name: tik-akkaseed
    build:
      context: ./TIK/Computation/AkkaSeed
      dockerfile: Dockerfile
    depends_on: 
      - tik.processservice.online
      - tik.processservice.batch

  tik.processservice.online:
    image: tik.processservice.online
    container-name: tik-online
    build:
      context: ./TIK/ProcessService/Online
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.computation.akka

  tik.processservice.identity:
    image: tik.processservice.identity
    container-name: tik-identity
    build:
      context: ./TIK/ProcessService/Identity
      dockerfile: Dockerfile

  tik.webportal:
    image: sripirom/tik.webportal
    container-name: tik-webportal
    build:
      context: ./TIK/WebPortal
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.processservice.online


