#docker-compose.yml (Base)
version: '2'

services:
  tik.computation.akkaseed:
    image: tik.computation.akkaseed
    container_name: tik-akkaseed
    build:
      context: ./Computation/AkkaSeed
      dockerfile: Dockerfile

  tik.processservice.online:
    image: tik.processservice.online
    container_name: tik-online
    build:
      context: ./ProcessService/Online
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.computation.akkaseed

  tik.processservice.identity:
    image: tik.processservice.identity
    container_name: tik-identity
    build:
      context: ./ProcessService/Identity
      dockerfile: Dockerfile

  tik.webportal:
    image: tik.webportal
    container_name: tik-webportal
    build:
      context: ./TIK.WebPortal
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.processservice.online


