#docker-compose.yml (Base)
version: '2'

services:
  tik.processservice.online:
    image: sripirom/tik.processservice.online
    build:
    context: ./TIK/ProcessService/Online
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity

  tik.processservice.batch:
    image: sripirom/tik.processservice.batch
    build:
    context: ./TIK/ProcessService/Batch
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity

  tik.processservice.identity:
    image: sripirom/tik.processservice.identity
    build:
    context: ./TIK/ProcessService/Identity
    dockerfile: Dockerfile
    depends_on:
      - sql.data

  tik.processservice.notification:
    image: sripirom/tik.processservice.notification
    build:
    context: ./TIK/ProcessService/Notification
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity

  tik.computation.akka:
    image: sripirom/tik.computation.akka
    build:
    context: ./TIK/Computation/Akka
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.online
      - tik.processservice.batch

  tik.computation.hangfire:
    image: sripirom/tik.computation.hangfire
    build:
    context: ./TIK/Computation/Hangfire
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.online

  tik.governance:
    image: sripirom/tik.governance
    build:
    context: ./TIK/Governance
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity

  tik.webportal:
    image: sripirom/tik.webportal
    build:
    context: ./TIK/WebPortal
    dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.processservice.online
      - tik.processservice.notification
      - tik.processservice.batch

  tik.webportal.signalr:
    image: sripirom/tik.webportal.signalr
    build:
    context: ./TIK/WebPortal.SignalR
    dockerfile: Dockerfile

  sql.data:
    image: microsoft/mssql-server-linux
    stock.data:
    image: redis
    expose:
      - "6379"
    rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

