#docker-compose.yml (Base)
version: '2'

services:
  tik.computation.akkaseed:
    image: tik.computation.akkaseed
    container_name: tik-akkaseed
    build:
      context: ./Computation/AkkaSeed
      dockerfile: Dockerfile
    depends_on:
      - consul3

  tik.processservice.online:
    image: tik.processservice.online
    container_name: tik-online
    build:
      context: ./ProcessService/Online
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.computation.akkaseed
      - consul2

  tik.processservice.identity:
    image: tik.processservice.identity
    container_name: tik-identity
    build:
      context: ./ProcessService/Identity
      dockerfile: Dockerfile
    depends_on:
      - consul2

  tik.webportal:
    image: tik.webportal
    container_name: tik-webportal
    build:
      context: ./TIK.WebPortal
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.processservice.online
      - consul1

  tik.websignalr:
    image: tik.websignalr
    container_name: tik-websignalr
    build:
      context: ./TIK.WebSignalR
      dockerfile: Dockerfile
    depends_on:
      - tik.processservice.identity
      - tik.processservice.online
      - consul2

  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"

  consul2:
    image: "progrium/consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    command: "-server -join consul1"
    depends_on:
      - consul1
      
  consul3:
    image: "progrium/consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    command: "-server -join consul1"
    depends_on:
      - consul1
