#docker-compose.override.yml (Extended config for DEVELOPMENT env.)
version: '2'

services:
# Simplified number of services here:
  tik.computation.akkaseed:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_AKKASEED_IP=0.0.0.0
      - TIK_AKKASEED_PORT=80
      - TIK_AKKASEED_HUCON=Hucon.txt
      - TIK_AKKASEED_ADDR=tik-akkaseed:5301
      - TIK_AKKASEED_SERVICENAME=tik-akkaseed
      - TIK_AKKASEED_HELPCHECK=/HealthCheck
      - TIK_AKKASEED_ENDPOINTS=http://tik-identity:80
      - CONSUL_HTTP_ENPOINT=http://consul3:8500
      - CONSUL_DNS_ADDRESS=consul3
      - CONSUL_DNS_PORT=8600
      - TIK_BATCH_URL=http://tik-batch
      - TIK_ACTORSYSTEM=OnlineSystem
    ports:
      - "5301:5301"
      - "5300:80"

  tik.processservice.online:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_ONLINE_IP=0.0.0.0
      - TIK_ONLINE_PORT=80
      - TIK_ONLINE_HUCON=Hucon.txt
      - TIK_ONLINE_SERVICENAME=tik-online
      - TIK_ONLINE_HELPCHECK=/HealthCheck
      - TIK_ONLINE_ENDPOINTS=http://tik-online:80
      - CONSUL_HTTP_ENPOINT=http://consul2:8500
      - CONSUL_DNS_PUBLISH_ADDRESS=192.168.1.36
      - CONSUL_DNS_ADDRESS=consul2
      - CONSUL_DNS_PORT=8600
      - CONSUL_DNS_BASEDOMAIN=service.consul
      - TIK_AKKASEED_ADDR=tik-akkaseed:5301
      - TIK_BATCH_URL=http://tik-batch
      - TIK_WEBSIGNALR_SERVICENAME=tik-websignalr
      - TIK_ACTORSYSTEM=OnlineSystem
    ports:
      - "5101:80"

  tik.processservice.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_IDENTITY_IP=0.0.0.0
      - TIK_IDENTITY_PORT=80
      - TIK_IDENTITY_SERVICENAME=tik-identity
      - TIK_IDENTITY_HELPCHECK=/HealthCheck
      - TIK_IDENTITY_ENDPOINTS=http://tik-identity:80
      - CONSUL_HTTP_ENPOINT=http://consul2:8500
      - CONSUL_DNS_ADDRESS=consul2
      - CONSUL_DNS_PORT=8600
    ports:
      - "5100:80"

  tik.webportal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_WEBPORTAL_IP=0.0.0.0
      - TIK_WEBPORTAL_PORT=80
      - TIK_WEBPORTAL_SERVICENAME=tik-webportal
      - TIK_WEBPORTAL_HELPCHECK=/HealthCheck
      - TIK_WEBPORTAL_ENDPOINTS=http://tik-webportal:80
      - CONSUL_HTTP_ENPOINT=http://consul1:8500
      - CONSUL_DNS_PUBLISH_ADDRESS=192.168.1.36
      - CONSUL_DNS_PORT=8600
      - CONSUL_DNS_BASEDOMAIN=service.consul
      - TIK_ONLINE_URL=http://tik-online
      - TIK_IDENTITY_URL=http://tik-identity
      - TIK_ONLINE_SERVICENAME=tik-online
      - TIK_IDENTITY_SERVICENAME=tik-identity
    ports:
      - "5000:80"

  tik.websignalr:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TIK_WEBSIGNALR_IP=0.0.0.0
      - TIK_WEBSIGNALR_PORT=80
      - TIK_WEBSIGNALR_SERVICENAME=tik-websignalr
      - TIK_WEBSIGNALR_HELPCHECK=/HealthCheck
      - TIK_WEBSIGNALR_ENDPOINTS=http://tik-websignalr:80
      - CONSUL_HTTP_ENPOINT=http://consul2:8500
      - CONSUL_DNS_ADDRESS=consul2
      - CONSUL_DNS_PORT=8600
      - TIK_WEBPORTAL_URL=http://tik-webportal
    ports:
      - "5001:80"

  consul1:
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"

  consul2:
    expose:
      - "8400"
      - "8500"
      - "8600"

  consul3:
    expose:
      - "8400"
      - "8500"
      - "8600"

