# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: T-I-K  asp.dotnetcore microservice 
email: pichit@sripirom.com
description: >- # this means to ignore newlines until "baseurl:"
  feature
    consul ServiceDiscovery
    Akka.NET computation state service
    SignalR broadcast realtime "add STOCK DISCUSSION"
    docker compose deployment .
    web angularjs
  services
  computation
    tik-akkaseed akka.net state actors processing
  processservice
    tik-identity	authentication token (jwt).
    tik-online	service webapi route to actors (akka.net).
  portal
    tik-webportal	angularjs UI route to process serviceses.
    tik-websignalr	signals broadcast to UI.

  service discovery
    consul1	server ui service discovery.
    consul2	children join consul1
    consul2 children join consul1
baseurl: "/T-I-K" # the subpath of your site, e.g. /blog
url: "https://sripirom.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sripiromPichit
github_username:  sripirom

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

